version: '2'

services:

### Applications Code Container #############################

    applications:
        image: tianon/true
        volumes:
            - ../src:/var/www
            - mysql:/var/lib/mysql
#            - ../sample/:/var/www/sample

### Workspace Utilities Container ###########################

    workspace:
        build:
            context: ./workspace
            args:
                - TZ=CDT
        volumes_from:
            - applications
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:192.168.99.100"
            - "cs-api.localhost:172.22.0.1"
            - "cs-stack.localhost:172.22.0.1"
        ports:
           - "2525:25"
        tty: true

### PHP-FPM Container #######################################

    php-fpm:
        build:
            context: ./php-fpm
            args:
                - INSTALL_XDEBUG=false
                - INSTALL_SOAP=false
                - INSTALL_MONGO=false
                - INSTALL_ZIP_ARCHIVE=false
                - INSTALL_BCMATH=false
                - INSTALL_MEMCACHED=false
                - INSTALL_OPCACHE=false
                - INSTALL_AEROSPIKE_EXTENSION=false
                - CODEIGNITER=true
            dockerfile: Dockerfile-53
        volumes_from:
            - applications
        expose:
            - "9000"
        links:
            - php53
            - workspace
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "dockerhost:192.168.99.100"
            # Get the IPs by going into nginx container and running:
            # /sbin/ip route|awk '/default/ { print $3 }'
            - "cs-api.localhost:172.22.0.1"
            - "cs-stack.localhost:172.22.0.1"
        environment:
            # IMPORTANT: Set the Remote Interpreter entry matching name to `cit`
            - PHP_IDE_CONFIG=serverName=cit

### PHP-FPM Container #######################################

    php53:
        build:
            context: ./php53
        volumes_from:
            - applications

### MySQL Container #########################################

    mysql:
        build: 
            context: ./mysql
            args:
                - MYSQL_DATABASE=citizenshipper
                - MYSQL_USER=darko
                - MYSQL_PASSWORD=secret
                - MYSQL_ROOT_PASSWORD=root
        volumes:
            - mysql:/var/lib/mysql
        ports:
            - "4306:3306"
        links:
            - workspace

### Apache Server Container #################################

    apache2:
        build:
            context: ./apache2
            args:
                - PHP_SOCKET=php-fpm:9000
        volumes_from:
            - applications
        volumes:
            - ./logs/apache2:/var/log/apache2
        extra_hosts:
            # IMPORTANT: Replace with your Docker Host IP (will be appended to /etc/hosts)
            - "cs-api.localhost:172.22.0.1"
            - "cs-stack.localhost:172.22.0.1"
        ports:
            - "6000:80"
            - "4434:443"
        links:
            - php-fpm

### Volumes Setup ###########################################

volumes:
    mysql:
        driver: "local"
    sessions:    ## nothing is connected to this (- ./data/sessions:/sessions)
        driver: "local"